format = """
$username$hostname\
[](fg:4 bg:0)\
$directory\
[](fg:0 bg:4)\
$git_branch\
$git_status\
[](fg:4)\
\n$character"""

[username]
show_always = true
style_user = "bg:4 fg:0"
style_root = "bg:4 fg:8"
format = "[ $user]($style)"

[hostname]
ssh_only = true
style = "bg:4 fg:0"
format = "[@$hostname]($style)"

[directory]
style = "fg:4 bg:0"
format = "[ $path]($style)"
truncation_length = 2
home_symbol = "~"
truncation_symbol = "…/"

[directory.substitutions]
"~/CAD" = "󰻬 "
"~/Code" = "󰈮 "
"~/Desktop" = "󰇄 "
"~/Documents" = "󰈙"
"~/Downloads" = " "
"~/OneDrive - issaquah.wednet.edu" = "󰏊 "
"~/.config" = " "

[git_branch]
symbol = ""
style = "fg:0 bg:4"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:0 bg:4"
format = '[( $all_status$ahead_behind)]($style)'

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
