general {
    # dbus/sysd lock command (triggered by loginctl lock-session)
    lock_cmd = pidof hyprlock || hyprlock 
    
    # lock before suspend
    before_sleep_cmd = loginctl lock-session 
    
    # to avoid having to press a key twice to turn on the display
    after_sleep_cmd = hyprctl dispatch dpms on 
}

listener {
    timeout = 150                                # 2.5 mins
    on-timeout = brightnessctl -s set 10         # dim screen
    on-resume = brightnessctl -r                 # restore brightness
}

listener {
    timeout = 300                                # 5 mins
    on-timeout = loginctl lock-session           # trigger lock
}

listener {
    timeout = 330                                # 5.5 mins
    on-timeout = hyprctl dispatch dpms off       # turn off screen
    on-resume = hyprctl dispatch dpms on         # turn on screen
}

listener {
    timeout = 1800                               # 30 mins
    on-timeout = systemctl suspend               # suspend pc
}
