source = ~/.cache/wal/colors-hyprland.conf

# BACKGROUND
background {
    monitor =
    path = ~/.cache/wal/lock-background.png
    color = $background
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# GREETINGS
label {
    monitor =
    text =<b>Welcome!</b>
    color = $foreground
    font_size = 55
    font_family = JetBrainsMono Nerd Font
    position = 295, 320
    halign = left
    valign = center
    shadow_passes = 2
    shadow_size = 3
    shadow_color = $background
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span weight='bold'>$(date +"%H:%M")</span>"
    color = $foreground
    font_size = 40
    font_family = JetBrainsMono Nerd Font
    position = 385, 240
    halign = left
    valign = center
    shadow_passes = 2
    shadow_size = 3
    shadow_color = $background
}

# Day-Month-Date
label {
    monitor =
    text =<b>Sunday, September 29</b>
    color = $foreground
    font_size = 20
    text_align = left
    font_family = JetBrainsMono Nerd Font
    position = 310, 175
    halign = left
    valign = center
    shadow_passes = 2
    shadow_size = 3
    shadow_color = $background
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = $foreground_a20
    rounding = -1
    border_size = 0
    border_color = $foreground
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 300, -140
    halign = left
    valign = center
}

# USER
label {
    monitor =
    text =  $USER
    color = $foreground
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 411, -140
    halign = left
    valign = center
    shadow_passes = 2
    shadow_size = 3
    shadow_color = $background
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = $foreground_a10
    font_color = $foreground
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i>🔒 Enter Pass</i>
    hide_input = false
    position = 300, -220
    halign = left
    valign = center
}
