preload = /home/cohen/Wallpapers/yosemite.png
preload = /home/cohen/Wallpapers/Clearday.jpg

wallpaper {
    monitor = 
    path = /home/cohen/Wallpapers/yosemite.png
    fit_mode = cover
}

splash = false

