# primary rendering on iGPU
env = AQ_DRM_DEVICES,/dev/dri/card0

env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = __GL_VRR_ALLOWED,0

env = GDK_SCALE,2
env = XCURSOR_SIZE,12

# monitor scale
monitor = eDP-1, preferred, auto, 2

xwayland {
	force_zero_scaling = true
}	

# cursor visibility fix
cursor {
	no_hardware_cursors = true
}

general {
	gaps_in = 5
	gaps_out = 5
	border_size = 1
}

input {
	touchpad {
		natural_scroll = true
		tap-to-click = true
	}
}

device {
	name = elan06b0:00-04f3:3327-touchpad
	sensitivity = 0.25
}

decoration {
	rounding = 12
}

animations {
	enabled = false
}

# autostart background services
exec-once = mako
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = elephant
exec-once = waybar
exec-once = walker --gapplication-service
exec-once = hypridle
exec-once = hyprpaper

# keybindings (functional defaults) 
$mainMod = SUPER

# applications
bind = $mainMod, Return, exec, ghostty
bind = $mainMod, E, exec, nautilus
bind = $mainMod, SPACE, exec, walker

# window managment
bind = $mainMod, Q, killactive,
bind = $mainMod, V, togglefloating, 
bind = $mainMod, F, fullscreen, 
bind = $mainMod, S, layoutmsg, togglesplit

# focus navigation
bind = $mainMod, J, movefocus, d,
bind = $mainMod, K, movefocus, u,
bind = $mainMod, H, movefocus, l,
bind = $mainMod, L, movefocus, r,

# workspace switching
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# workspace moving
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# exit hyprland to tty
bind = $mainMod SHIFT, M, exit,

# audio/volume controls
bindel = , XF86AudioRaiseVolCUme, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolCUme, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# screenshots
bind = , PRINT, exec, hyprshot -m output
bind = $mainMod, PRINT, exec, hyprshot -m region

debug {
	disable_logs = false
}
