preload = /home/cohen/Pictures/wallpapers/a_tree_in_a_body_of_water_with_mountains_in_the_background.jpg

wallpaper {
    monitor = 
    path = /home/cohen/Pictures/wallpapers/a_tree_in_a_body_of_water_with_mountains_in_the_background.jpg
    fit_mode = cover
}

splash = false

