unbind r
bind r source-file ~/.tmux.conf

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"
set -g default-command "$SHELL -l"

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-plugins "time"
set -g @dracula-time-format "%H:%M %a %d %b"
set -g @dracula-show-left-icon session
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g status-position top

run '~/.tmux/plugins/tpm/tpm'
